version: "3.8"

services:
  redis:
    container_name: rate-limiter_redis
    image: redis:7.2.4-alpine3.19
    env_file: .env
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis-data:/data
    networks:
      - default

  k6:
    container_name: rate-limiter_k6
    image: grafana/k6:latest
    ports:
      - "6565:6565"
    volumes:
      - ./scripts/k6:/scripts
    networks:
      - default
    environment:
      - K6_WEB_DASHBOARD=true

  api:
    container_name: rate-limiter_api
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "${WEB_SERVER_PORT:-8080}:8080"
    networks:
      - default
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT:-6379}
    volumes:
      - ./.env:/app/.env

volumes:
  redis-data:

networks:
  default: